### ISSUE TITLE
Error . I cant use images in application (no images)

### ISSUE THREAD

**Issue by fredcox** [codesbiome/electron-react-webpack-typescript-2020#1]
Hi, 

I write the following code: 

`import avril from '../avril.jpg';`

In render i put:

`<img src={avril} />`

And i get the error: 

`ERROR in ./src/app/components/App.tsx
Module not found: Error: Can't resolve '../avril.jpg' in 'C:\Users\fredc\Documents\Projetos\teste\src\app\components`

Well, maybe the webpack not possible to user images with electron and react configuration. 

I never see one boilerplate (React+Webpack+Electron) with images OK.

**Comment by codesbiome** [comment]
Hello there,

I will also be adding the image/url loader asap. 
Also thinking about including a font-loader too in case people need that stuff.

Thanks for the heads up
Cheers!

**Comment by codesbiome** [comment]
Made some changes and tweaks regarding the issue, following are the few of them : 

f6a6a1c8001be90738538d477a318a730332b9df : Using custom aliases for path resolving
c48fcbf9669d0624b155895e843122673dc20f3d : Supporting image loader for boilerplate

Would be nice if you could provide confirmation of things working fine during dev and prod mode.
Cheers!
