### ISSUE TITLE
Problems with adding tedious

### ISSUE THREAD

**Issue by ulou** [codesbiome/electron-react-webpack-typescript-2020#4]
Hi!

Just installed dependency using `yarn add tedious` and `yarn add @types/tedious` , then tried to do simply connection, but looks like it's not possible cause I got following error:
```
Uncaught ReferenceError: require is not defined
    at Object.events (index.js:140122)
    at __webpack_require__ (index.js:790)
    at fn (index.js:101)
    at Object../node_modules/tedious/lib/bulk-load.js (index.js:99091)
    at __webpack_require__ (index.js:790)
    at fn (index.js:101)
    at Object../node_modules/tedious/lib/tedious.js (index.js:110052)
    at __webpack_require__ (index.js:790)
    at fn (index.js:101)
    at Module../src/app/database/sqlService.ts (index.js:139762)
```

looks like it comes from `module.exports = require("events");` from `tedious`. There are a lot of answers in google about similar problems, that I should enable `nodeIntegration`. I don't think so thats it in this case, but anyway I've tried and it didn't work either.

Code:
```
export const connectToDb = (): Promise<Connection> => {
  return new Promise((resolve, reject) => {
    const config = {
      authentication: {
        options: {
          userName: "sa", // update me
          password: "" // update me
        },
        type: "default"
      },
      server: "test_gt_db@localhost", // update me
      options: {
        database: "test", //update me
        encrypt: true
      }
    }
    const connection = new Connection(config) // it breaks here
  })
} 
```

**Comment by codesbiome** [comment]
Hello ulou,

> looks like it comes from module.exports = require("events"); from tedious. There are a lot of answers in google about similar problems, that I should enable nodeIntegration. I don't think so thats it in this case, but anyway I've tried and it didn't work either.

Can you try the same process with following `WebPreference` configuration in `main.ts` file for Electron Window.

```jsonc
    webPreferences: {
      nodeIntegration: true, // Changed 
      enableRemoteModule: false,
      contextIsolation: false, // Changed
      nodeIntegrationInWorker: false,
      nodeIntegrationInSubFrames: false,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
```

Following is the `console.log` output of `Connection` when having the configuration updated and using the source code you mentioned above:

![image](https://user-images.githubusercontent.com/46080054/99267847-7a54c980-284a-11eb-86b6-ffc2edbf3d94.png)

Lemme know if you still face the same issue
Cheers!

**Comment by ulou** [comment]
Hey @codesbiome,
thanks for the answer, I forgot to answer here. Your suggestion is correct, that's exactly how I fixed this.

My question and answer:
https://stackoverflow.com/questions/64706829/electron-tedious-requireevents-is-not-defined

**Comment by codesbiome** [comment]
Hello @ulou 

Good to know its working fine.
Thanks for confirmation,
Cheers!
